### ISSUE TITLE
[Regarding URL rewriting]

### ISSUE THREAD

**Issue by brickfreelayer** [tsepomaleka/OpenCode#1]
Hi Tsepo, your tutorial is great, I just have this question here. Once you deploy your project, why could my project does not have any input fields? Have you used URL rewriting but have not documented inside your tutorial?

**Comment by tsepomaleka** [comment]
@brickfreelayer I did not use any URL rewriting in my tutorial. If you integrate JSF into your Spring Boot application, you lose the extensionless URLs as one would normally get with using Spring's controllers. 
There's third party libraries that you can use to rewrite your URLs if you do not like the .xhtml extensions online. Personally, there isn't one I have used before. 

Another options is, you can write a request dispatcher that can map your extensionless URLs to XHTML extensions.

**Comment by brickfreelayer** [comment]
Thanks for your response. I'm new on the integration and I think your tutorial here is a good "HelloWorld" one. This path is not a beaten one, so thanks for your help!
